
/*
	author: xuhailong
	date: 2011-4-18
	msn: hailongxu@msn.com
	Hi: hailonghsu@baidu.com

	this is a free and open code
	you can use it freely, but you should include the author declaration
 */


#pragma once


#define MACRO_JOIN(x,y) x##y
#define MACRO_JOIN2(x,n,y) x##n y##n
#define MACRO_INIT_JOIN2(x,n,y) x##n(y##n)
#define MACRO_ASSIGN_JOIN2(x,n,o) this->x##n=o.x##n
#define MACRO_ASSIGN_FROM_PARAM_JOIN2(x,n,y) this->x##n=y##n
#define MACRO_BRACKET_JOIN3(x,y,z) x##(y)##z


#define MACRO_ACTIVE1_1(s) MACRO_JOIN(s,1)
#define MACRO_ACTIVE1_2(s) MACRO_ACTIVE1_1(s),MACRO_JOIN(s,2)
#define MACRO_ACTIVE1_3(s) MACRO_ACTIVE1_2(s),MACRO_JOIN(s,3)
#define MACRO_ACTIVE1_4(s) MACRO_ACTIVE1_3(s),MACRO_JOIN(s,4)
#define MACRO_ACTIVE1_5(s) MACRO_ACTIVE1_4(s),MACRO_JOIN(s,5)
#define MACRO_ACTIVE1_6(s) MACRO_ACTIVE1_5(s),MACRO_JOIN(s,6)
#define MACRO_ACTIVE1_7(s) MACRO_ACTIVE1_6(s),MACRO_JOIN(s,7)
#define MACRO_ACTIVE1_8(s) MACRO_ACTIVE1_7(s),MACRO_JOIN(s,8)
#define MACRO_ACTIVE1_9(s) MACRO_ACTIVE1_8(s),MACRO_JOIN(s,9)

#define MACRO_ACTIVE_BRACKET_AnB_1(s,s2) MACRO_BRACKET_JOIN3(s,1,s2)
#define MACRO_ACTIVE_BRACKET_AnB_2(s,s2) MACRO_ACTIVE_BRACKET_AnB_1(s,s2)MACRO_BRACKET_JOIN3(s,2,s2)
#define MACRO_ACTIVE_BRACKET_AnB_3(s,s2) MACRO_ACTIVE_BRACKET_AnB_2(s,s2)MACRO_BRACKET_JOIN3(s,3,s2)
#define MACRO_ACTIVE_BRACKET_AnB_4(s,s2) MACRO_ACTIVE_BRACKET_AnB_3(s,s2)MACRO_BRACKET_JOIN3(s,4,s2)
#define MACRO_ACTIVE_BRACKET_AnB_5(s,s2) MACRO_ACTIVE_BRACKET_AnB_4(s,s2)MACRO_BRACKET_JOIN3(s,5,s2)
#define MACRO_ACTIVE_BRACKET_AnB_6(s,s2) MACRO_ACTIVE_BRACKET_AnB_5(s,s2)MACRO_BRACKET_JOIN3(s,6,s2)
#define MACRO_ACTIVE_BRACKET_AnB_7(s,s2) MACRO_ACTIVE_BRACKET_AnB_6(s,s2)MACRO_BRACKET_JOIN3(s,7,s2)
#define MACRO_ACTIVE_BRACKET_AnB_8(s,s2) MACRO_ACTIVE_BRACKET_AnB_7(s,s2)MACRO_BRACKET_JOIN3(s,8,s2)
#define MACRO_ACTIVE_BRACKET_AnB_9(s,s2) MACRO_ACTIVE_BRACKET_AnB_8(s,s2)MACRO_BRACKET_JOIN3(s,9,s2)


#define MACRO_ACTIVE2_1(s,s2) MACRO_JOIN2(s,1,s2)
#define MACRO_ACTIVE2_2(s,s2) MACRO_ACTIVE2_1(s,s2),MACRO_JOIN2(s,2,s2)
#define MACRO_ACTIVE2_3(s,s2) MACRO_ACTIVE2_2(s,s2),MACRO_JOIN2(s,3,s2)
#define MACRO_ACTIVE2_4(s,s2) MACRO_ACTIVE2_3(s,s2),MACRO_JOIN2(s,4,s2)
#define MACRO_ACTIVE2_5(s,s2) MACRO_ACTIVE2_4(s,s2),MACRO_JOIN2(s,5,s2)
#define MACRO_ACTIVE2_6(s,s2) MACRO_ACTIVE2_5(s,s2),MACRO_JOIN2(s,6,s2)
#define MACRO_ACTIVE2_7(s,s2) MACRO_ACTIVE2_6(s,s2),MACRO_JOIN2(s,7,s2)
#define MACRO_ACTIVE2_8(s,s2) MACRO_ACTIVE2_7(s,s2),MACRO_JOIN2(s,8,s2)
#define MACRO_ACTIVE2_9(s,s2) MACRO_ACTIVE2_8(s,s2),MACRO_JOIN2(s,9,s2)

#define MACRO_ACTIVE2C_1(s,s2) MACRO_JOIN2(s,1,s2);
#define MACRO_ACTIVE2C_2(s,s2) MACRO_ACTIVE2C_1(s,s2)MACRO_JOIN2(s,2,s2);
#define MACRO_ACTIVE2C_3(s,s2) MACRO_ACTIVE2C_2(s,s2)MACRO_JOIN2(s,3,s2);
#define MACRO_ACTIVE2C_4(s,s2) MACRO_ACTIVE2C_3(s,s2)MACRO_JOIN2(s,4,s2);
#define MACRO_ACTIVE2C_5(s,s2) MACRO_ACTIVE2C_4(s,s2)MACRO_JOIN2(s,5,s2);
#define MACRO_ACTIVE2C_6(s,s2) MACRO_ACTIVE2C_5(s,s2)MACRO_JOIN2(s,6,s2);
#define MACRO_ACTIVE2C_7(s,s2) MACRO_ACTIVE2C_6(s,s2)MACRO_JOIN2(s,7,s2);
#define MACRO_ACTIVE2C_8(s,s2) MACRO_ACTIVE2C_7(s,s2)MACRO_JOIN2(s,8,s2);
#define MACRO_ACTIVE2C_9(s,s2) MACRO_ACTIVE2C_8(s,s2)MACRO_JOIN2(s,9,s2);

#define MACRO_ACTIVE2INIT_1(s,s2) MACRO_INIT_JOIN2(s,1,s2)
#define MACRO_ACTIVE2INIT_2(s,s2) MACRO_ACTIVE2INIT_1(s,s2),MACRO_INIT_JOIN2(s,2,s2)
#define MACRO_ACTIVE2INIT_3(s,s2) MACRO_ACTIVE2INIT_2(s,s2),MACRO_INIT_JOIN2(s,3,s2)
#define MACRO_ACTIVE2INIT_4(s,s2) MACRO_ACTIVE2INIT_3(s,s2),MACRO_INIT_JOIN2(s,4,s2)
#define MACRO_ACTIVE2INIT_5(s,s2) MACRO_ACTIVE2INIT_4(s,s2),MACRO_INIT_JOIN2(s,5,s2)
#define MACRO_ACTIVE2INIT_6(s,s2) MACRO_ACTIVE2INIT_5(s,s2),MACRO_INIT_JOIN2(s,6,s2)
#define MACRO_ACTIVE2INIT_7(s,s2) MACRO_ACTIVE2INIT_6(s,s2),MACRO_INIT_JOIN2(s,7,s2)
#define MACRO_ACTIVE2INIT_8(s,s2) MACRO_ACTIVE2INIT_7(s,s2),MACRO_INIT_JOIN2(s,8,s2)
#define MACRO_ACTIVE2INIT_9(s,s2) MACRO_ACTIVE2INIT_8(s,s2),MACRO_INIT_JOIN2(s,9,s2)

#define MACRO_ACTIVE2ASSIGN_1(s,s2) MACRO_ASSIGN_JOIN2(s,1,s2);
#define MACRO_ACTIVE2ASSIGN_2(s,s2) MACRO_ACTIVE2ASSIGN_1(s,s2)MACRO_ASSIGN_JOIN2(s,2,s2);
#define MACRO_ACTIVE2ASSIGN_3(s,s2) MACRO_ACTIVE2ASSIGN_2(s,s2)MACRO_ASSIGN_JOIN2(s,3,s2);
#define MACRO_ACTIVE2ASSIGN_4(s,s2) MACRO_ACTIVE2ASSIGN_3(s,s2)MACRO_ASSIGN_JOIN2(s,4,s2);
#define MACRO_ACTIVE2ASSIGN_5(s,s2) MACRO_ACTIVE2ASSIGN_4(s,s2)MACRO_ASSIGN_JOIN2(s,5,s2);
#define MACRO_ACTIVE2ASSIGN_6(s,s2) MACRO_ACTIVE2ASSIGN_5(s,s2)MACRO_ASSIGN_JOIN2(s,6,s2);
#define MACRO_ACTIVE2ASSIGN_7(s,s2) MACRO_ACTIVE2ASSIGN_6(s,s2)MACRO_ASSIGN_JOIN2(s,7,s2);
#define MACRO_ACTIVE2ASSIGN_8(s,s2) MACRO_ACTIVE2ASSIGN_7(s,s2)MACRO_ASSIGN_JOIN2(s,8,s2);
#define MACRO_ACTIVE2ASSIGN_9(s,s2) MACRO_ACTIVE2ASSIGN_8(s,s2)MACRO_ASSIGN_JOIN2(s,9,s2);

#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_1(s,s2) MACRO_ASSIGN_FROM_PARAM_JOIN2(s,1,s2);
#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_2(s,s2) MACRO_ACTIVE2ASSIGN_FROM_PARAM_1(s,s2)MACRO_ASSIGN_FROM_PARAM_JOIN2(s,2,s2);
#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_3(s,s2) MACRO_ACTIVE2ASSIGN_FROM_PARAM_2(s,s2)MACRO_ASSIGN_FROM_PARAM_JOIN2(s,3,s2);
#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_4(s,s2) MACRO_ACTIVE2ASSIGN_FROM_PARAM_3(s,s2)MACRO_ASSIGN_FROM_PARAM_JOIN2(s,4,s2);
#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_5(s,s2) MACRO_ACTIVE2ASSIGN_FROM_PARAM_4(s,s2)MACRO_ASSIGN_FROM_PARAM_JOIN2(s,5,s2);
#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_6(s,s2) MACRO_ACTIVE2ASSIGN_FROM_PARAM_5(s,s2)MACRO_ASSIGN_FROM_PARAM_JOIN2(s,6,s2);
#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_7(s,s2) MACRO_ACTIVE2ASSIGN_FROM_PARAM_6(s,s2)MACRO_ASSIGN_FROM_PARAM_JOIN2(s,7,s2);
#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_8(s,s2) MACRO_ACTIVE2ASSIGN_FROM_PARAM_7(s,s2)MACRO_ASSIGN_FROM_PARAM_JOIN2(s,8,s2);
#define MACRO_ACTIVE2ASSIGN_FROM_PARAM_9(s,s2) MACRO_ACTIVE2ASSIGN_FROM_PARAM_8(s,s2)MACRO_ASSIGN_FROM_PARAM_JOIN2(s,9,s2);


#define DEF_TYPENAMES(n) MACRO_ACTIVE1_##n(typename p)
#define DEF_TYPENAMES2(p,n) MACRO_ACTIVE1_##n(typename p)
#define DEF_TYPES(n) MACRO_ACTIVE1_##n(p)
#define DEF_TYPES2(p,n) MACRO_ACTIVE1_##n(p)
#define DEF_OBJS(n) MACRO_ACTIVE1_##n(_p)
#define DEF_OBJS2(p,n) MACRO_ACTIVE1_##n(_##p)
#define DEF_ARGS(n) MACRO_ACTIVE2_##n(p,_p)
#define DEF_ARGS2(p,n) MACRO_ACTIVE2_##n(p,_##p)
#define DEF_MEMBS_DEF(n) MACRO_ACTIVE2C_##n(p,_m_p)
#define DEF_MEMBS(n) MACRO_ACTIVE1_##n(_m_p)
#define DEF_MEMBS_INIT(n) MACRO_ACTIVE2INIT_##n(_m_p,_p)
#define DEF_MEMBS_ASSIGN(n) MACRO_ACTIVE2ASSIGN_##n(_m_p,o)
#define DEF_MEMBS_ASSIGN_FROMPARAM(n) MACRO_ACTIVE2ASSIGN_FROM_PARAM_##n(_m_p,_p)
#define DEF_BRACKET_REPEAT(a,n,b) MACRO_ACTIVE_BRACKET_AnB_##n(a,b)


#define DEF_STRING(s) DEF_STRING2(s)
#define DEF_STRING2(s) #s


/*
	used
 */